{
  "formatVersion": "1.1",
  "component": {
    "group": "de.genflux",
    "module": "gradle-dev",
    "version": "6.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lamtztwxpzgi3p2nhxtl2sqabu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gradle-dev-6.8.3.jar",
          "url": "gradle-dev-6.8.3.jar",
          "size": 65778869,
          "sha512": "b2fffc14e79a5bd6eb36448a56794c73b841bfad61a0e3a247a3e337ad1c048c99d0feff34e9dfe4f26e75298595be80dea04280717939802661e6db6ea7b51b",
          "sha256": "3f7908cabbf930c641a30b7b333feda16399c0561b26ca016b72c1f668766aa2",
          "sha1": "4eac8801f5bc9df9cf0bd7413ec768b69698c771",
          "md5": "6b4d7fb9194f6cd98754fb7d4b130309"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-dev-6.8.3.jar",
          "url": "gradle-dev-6.8.3.jar",
          "size": 65778869,
          "sha512": "b2fffc14e79a5bd6eb36448a56794c73b841bfad61a0e3a247a3e337ad1c048c99d0feff34e9dfe4f26e75298595be80dea04280717939802661e6db6ea7b51b",
          "sha256": "3f7908cabbf930c641a30b7b333feda16399c0561b26ca016b72c1f668766aa2",
          "sha1": "4eac8801f5bc9df9cf0bd7413ec768b69698c771",
          "md5": "6b4d7fb9194f6cd98754fb7d4b130309"
        }
      ]
    }
  ]
}
